import random
username = 'ivankanowak'
password = 'In270205'

GPTSECRET = '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'
FOOCUS_API_SECRET = ''

# make prompt
# at [public location] wearing revealing [colour] [outfit adjective] [outfits] [pose] [skinstring]\
skinstring = 'big breasts ,skin has freckles, acne, stretchmarks'


#400
public_locations = [
    "Beach", "Pool", "Park", "Library", "Museum", 
    "Restaurant", "Cafe", "Gym", "School", "College", 
    "Hospital", "Shopping mall", "Airport", "Train station", 
    "Bus stop", "Movie theater", "Concert hall", "Stadium", 
    "Amusement park", "Zoo", "Office building", "City square", 
    "Botanical garden", "Art gallery", "Skating rink", 
    "Bowling alley", "Community center", "Farmers market", 
    "Ice cream shop", "Historical landmark", "Marina", 
    "Pet store", "Planetarium", "Race track", "Waterfall", 
    "Campground", "Mountain trail", "Bookstore", "Coffee shop", 
    "Fitness studio", "Dance studio", "Playground", "Game arcade", 
    "Karaoke bar", "Bakery", "Cinema", "Gas station", "Grocery store", 
    "City park", "Beach boardwalk", "Lighthouse", "Bridge", 
    "Botanical park", "Winery", "Science museum", "Aquarium", 
    "Farm", "Nature reserve", "Ski resort", "Hotel", "Sculpture garden", 
    "Water park", "Public garden", "Observatory", "Monument", 
    "Food court", "Flea market", "Radio station", "TV studio", 
    "Farmers' market", "Observation deck", "Casino", "Shopping center", 
    "Historic site", "Waterfront", "Toy store", "Dentist office", 
    "Yoga studio", "Barbershop", "Juice bar", "City hall", "Fire station", 
    "Police station", "Post office", "Train depot", "Boat dock", 
    "Skate park", "Mini golf course", "Recycling center", "Cemetery", 
    "Synagogue", "Church", "Mosque", "Temple", "City beach", 
    "Art studio", "Dog park", "Campsite", "Bike trail", "Hiking trail", 
    "Botanical greenhouse", "Natural history museum", "Fireworks show", 
    "Beer garden", "Cultural center", "Festival grounds", "Town square", 
    "Music venue", "Synthetic ice rink", "Curling rink", "Rock climbing gym", 
    "Ropes course", "Wine bar", "Whale watching spot", "Observation tower", 
    "Helipad", "Helicopter tour", "Radio tower", "Lighthouse beach", 
    "Bungee jumping platform", "Waterfront promenade", "Historic district", 
    "Train museum", "Classic car show", "Golf course", "Putting green", 
    "Driving range", "Horse riding arena", "Ampitheater", "Comedy club", 
    "Planetarium", "Circus tent", "Haunted house", "Escape room", 
    "Trampoline park", "Roller rink", "Dive bar", "Beer festival", 
    "Wine tasting room", "Drive-in theater", "Dog show", "Botanical arboretum", 
    "Bee farm", "Petting zoo", "Boutique", "Laser tag arena", "Bowling green", 
    "Indoor climbing wall", "Skydiving center", "Hot air balloon ride", 
    "Botanical sanctuary", "Indoor trampoline park", "Water sports rental", 
    "Sailing school", "Surfing school", "Rooftop bar", "Dolphin show", 
    "Historic bridge", "Historic mansion", "Paddleboarding rental", 
    "Kiteboarding spot", "Marine biology institute", "Oyster bar", 
    "Public market", "Historic battlefield", "Beachfront restaurant", 
    "Public square", "Artisanal shop", "Urban farm", "Paintball field", 
    "Bumper cars arena", "Go-kart track", "Climbing gym", "Indoor go-karting", 
    "Cheese shop", "Hot spring", "Desert oasis", "Cave exploration site", 
    "Railroad museum", "Microbrewery", "Bonsai garden", "Aquaponics farm", 
    "Tea house", "Bubble tea shop", "Retro arcade", "Escape room center", 
    "Beekeeping farm", "Roller coaster park", "Canopy walkway", 
    "Historic trail", "Vineyard", "Beer cellar", "Bike park", "Antique shop","Beach",
    "Park",
    "Botanical garden",
    "Zoo",
    "Art museum",
    "Historical site",
    "Mountain trail",
    "Countryside picnic spot",
    "Spa retreat",
    "Winery tour",
    "Outdoor concert venue",
    "Amusement park",
    "Planetarium",
    "Sculpture garden",
    "Hot air balloon ride",
    "City rooftop bar",
    "River cruise",
    "Bike trail",
    "Lighthouse",
    "Flea market",
    "Sunset cruise",
    "Historic town tour",
    "Lakefront walk",
    "Bookstore cafe",
    "Cooking class",
    "Public garden",
    "Boardwalk by the sea",
    "Gourmet food festival",
    "Cultural festival",
    "Horseback riding trail",
    "Outdoor movie night",
    "Jazz club",
    "Ice skating rink",
    "Yoga retreat",
    "Escape room challenge",
    "Guided city tour",
    "Nature reserve",
    "Antique shopping",
    "Wine and paint night",
    "Stargazing at an observatory",
    "Gondola ride",
    "Ballet performance",
    "Pottery class",
    "Historical mansion tour",
    "Tropical beach resort",
    "Waterfall hike",
    "Sailing excursion",
    "Scenic helicopter tour",
    "Public art installation",
    "Botanical greenhouse",
    "Wine tasting at a vineyard",
    "Outdoor sculpture trail",
    "Champagne brunch cruise",
    "Massage workshop",
    "Brewery tour",
    "Tram ride through the mountains",
    "Horse carriage ride",
    "Picnic in a botanical park",
    "Dance class",
    "Jogging path along the river",
    "Balloon festival",
    "Historic train ride",
    "Paddleboarding expedition",
    "Amphitheater concert",
    "Bird watching sanctuary",
    "Beachfront bonfire",
    "Historical walking tour",
    "Forest cabin retreat",
    "Art gallery opening",
    "Seafood cooking class",
    "Historic garden tour",
    "Astronomy night",
    "Zip-lining adventure",
    "Street food market",
    "Lakeside bed and breakfast",
    "Photography session",
    "Ski resort getaway",
    "Dolphin watching tour",
    "Salsa dancing night",
    "Kayaking expedition",
    "Cultural museum visit",
    "Chocolate tasting event",
    "Improv comedy show",
    "Wildlife safari",
    "Scenic train ride",
    "Moonlit beach walk",
    "Meditation retreat",
    "Rock climbing gym",
    "Bike tour",
    "Historical battlefield visit",
    "Music festival",
    "Horseback trail ride",
    "Archery lesson",
    "Lantern-lit garden evening",
    "Winery visit",
    "Hot air balloon safari",
    "Trail run",
    "Food truck festival",
    "Stand-up paddleboarding",
    "Cherry blossom festival",
    "Haunted house tour",
    "Themed costume party",
    "Ballroom dancing event",
    "Mosaic art class",
    "Acrobatics class",
    "Classic car show",
    "Historical reenactment",
    "Pottery painting",
    "ATV adventure",
    "Underwater photography",
    "Canoeing",
    "Stargazing",
    "Trapeze class",
    "Snorkeling expedition",
    "Carriage ride",
    "Birding excursion",
    "Calligraphy class",
    "Dinner theater",
    "Kite flying",
    "3D printing workshop",
    "Laser tag",
    "Eco-friendly retreat",
    "Hot air balloon ride",
    "Eco-friendly workshop",
    "Horseback archery",
    "Trolley tour",
    "Segway tour",
    "Geocaching adventure",
    "Drone flying experience",
    "Horseback jousting",
    "Letterpress printing",
    "Kite surfing lesson",
    "Foraging expedition",
    "Hot air balloon glow",
    "Virtual escape room",
    "Virtual wine tasting",
    "Wildlife tracking",
    "Virtual cooking class",
    "Virtual art gallery tour",
    "Virtual dance party",
    "Virtual travel experience",
]
#70
summer_clothes_female = [
    "Sundress",
    "Tank top",
    "Shorts",
    "Maxi skirt",
    "Crop top",
    "Bikini",
    "Straw hat",
    "Sunglasses",
    "Flip-flops",
    "Sandals",
    "Beach cover-up",
    "Off-the-shoulder top",
    "Denim shorts",
    "Rompers",
    "T-shirt dress",
    "Swim cover-up",
    "Espadrilles",
    "Wide-brimmed hat",
    "Cotton shorts",
    "Wrap dress",
    "Pleated skirt",
    "Linen blouse",
    "High-waisted shorts",
    "Boho maxi dress",
    "One-piece swimsuit",
    "Ruffled top",
    "Jumpsuit",
    "Floppy hat",
    "Slides",
    "Cut-off shorts",
    "Kimono",
    "Cropped trousers",
    "Halter neck top",
    "Strappy sandals",
    "Beach tote bag",
    "Lace-up sandals",
    "Floral print dress",
    "Mesh cover-up",
    "Paperbag shorts",
    "Tie-front blouse",
    "Printed jumpsuit",
    "Jersey knit dress",
    "Palazzo pants",
    "Tropical print romper",
    "High-low maxi dress",
    "Embroidered sundress",
    "Chiffon beach pants",
    "Cold shoulder top",
    "Bohemian tunic",
    "Midi wrap dress",
    "Tucked blouse, high trousers",
    "Off-shoulder, knee-length skirt",
    "Skinny jeans, fitted tank",
    "Mini skirt, crop top",
    "Low-cut halter dress",
    "Shorts, off-shoulder sweater",
    "Deep V-neck jumpsuit",
    "Bodysuit, wide-leg pants",
    "Asymmetric dress, ankle boots",
    "Sheer blouse, pencil skirt",
    "Shorts, tie-front blouse",
    "Midi dress, ankle strap heels",
    "Plunging romper, wedges",
    "Cropped sweater, culottes",
    "Bodycon dress, statement earrings",
    "Maxi wrap dress, side slit",
    "Ruffled crop top, denim shorts",
    "Blazer, lace camisole, jeans",
    "Turtleneck, pencil skirt",
    "Sleeveless jumpsuit, cinched waist",
]
#20
colors = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Purple",
    "Orange",
    "Pink",
    "Turquoise",
    "Brown",
    "Gray",
    "Black",
    "White",
    "Magenta",
    "Cyan",
    "Lime",
    "Teal",
    "Indigo",
    "Maroon",
    "Navy",
    "Olive",
]
#20
female_model_poses = [
    "Classic Portrait Pose",
    "Fashion Runway Strut",
    "Casual Walking Pose",
    "Elegant Back Arch",
    "Seated Cross-Legged Pose",
    "Dramatic Hair Flip",
    "Power Stance",
    "Runway Spin and Stop",
    "Leaning Against a Wall",
    "Sitting on a Stool",
    "Candid Laughing Pose",
    "Profile Silhouette Pose",
    "Graceful Twirl",
    "Head Tilt with Confidence",
    "Over-the-Shoulder Glance",
    "Sitting Cross-Legged on the Floor",
    "Reaching for the Sky",
    "Dynamic Jump or Leap",
    "Playful Skipping Pose",
    "Relaxed Sitting on Steps",
]
#100
summer_clothing_adjectives = [
    "Breezy",
    "Vibrant",
    "Effortless",
    "Sunny",
    "Playful",
    "Chic",
    "Airy",
    "Radiant",
    "Whimsical",
    "Relaxed",
    "Flirty",
    "Cheerful",
    "Striking",
    "Cool",
    "Lively",
    "Carefree",
    "Feminine",
    "Splashy",
    "Graceful",
    "Beachy",
    "Lightweight",
    "Colorful",
    "Refreshing",
    "Casual",
    "Spirited",
    "Luminous",
    "Laid-back",
    "Enchanting",
    "Trendy",
    "Elegant",
    "Breathtaking",
    "Dazzling",
    "Sizzling",
    "Delightful",
    "Sultry",
    "Glamorous",
    "Bold",
    "Sensual",
    "Exotic",
    "Mesmerizing",
    "Alluring",
    "Dynamic",
    "Tropical",
    "Charming",
    "Captivating",
    "Eclectic",
    "Joyful",
    "Stylish",
    "Exuberant",
    "Sunkissed",
    "Sassy",
    "Serene",
    "Ethereal",
    "Adventurous",
    "Festive",
    "Elevated",
    "Inventive",
    "Spontaneous",
    "Floral",
    "Free-spirited",
    "Uplifting",
    "Glittering",
    "Dainty",
    "Ravishing",
    "Lively",
    "Effervescent",
    "Opulent",
    "Dashing",
    "Enigmatic",
    "Quirky",
    "Sizzling",
    "Unforgettable",
    "Magnetic",
    "Dynamic",
    "Intriguing",
    "Epic",
    "Dramatic",
    "Sun-kissed",
    "Fascinating",
    "Swirling",
    "Unconventional",
    "Adorned",
    "Frolicsome",
    "Velvety",
    "Sensual",
    "Funky",
    "Scintillating",
    "Regal",
    "Balletic",
    "Unabashed",
    "Fervent",
    "Vivid",
    "Frothy",
    "Ephemeral",
    "Voguish",
    "Zesty",
    "Radiant",
]


lewd = []

def promptgenerate():
    prompt = "at " + random.choice(public_locations) + " wearing revealing " + random.choice(colors) + ' ' + random.choice(summer_clothing_adjectives) + ' ' + random.choice(summer_clothes_female) + ' ' + random.choice(female_model_poses) + ' ' + skinstring
    return prompt

